---
apiVersion: v1
kind: Service
metadata:
  name: facebook-service
spec:
  selector:
    app: facebook
    version: blue # Initially pointing to the blue deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: LoadBalancer
